# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30cbf3fb617e6da911848beb279e3dd98065f8c06e2513752b55f371413e0b50f3d4de9da9e2182081520c9fc0b57e01a76179a6ee0161012aa520cc1cb61e34

test:
  secret_key_base: c3cef7c974ef091c63e23a7b974b475fae4634040bef169b68164c83302e1772598f85ed478c93d8928884d5a016c94cd33d7e10d01330328939173fe4e41a44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
